stages:
    - build
    - release

build:
    stage: build
    only:
        - master
    script:
        - docker build -t mgkeiji/kcommerce .

release:
    stage: release
    only:
        - master
    script:
        - echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin
        - docker push mgkeiji/kcommerce