version: '3'

services:

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: keiji
      MYSQL_PASSWORD: somepassword
      MYSQL_ROOT_PASSWORD: somepassword

  kcommerce:
    tty: true 
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    links:
      - mysql:kcommerce
    depends_on:
      - mysql
    ports:
      - 80:3000
    volumes:
      - .:/myapp
